apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "jellyfin.name" . }}-pv-config
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.configDataPath }}
