kind: Service
apiVersion: v1
metadata:
  name: {{ include "jellyfin.fullname" . }}-udp  
  annotations:
    purelb.io/allow-shared-ip: {{ include "jellyfin.name" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "jellyfin.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - port: 1900
    targetPort: 1900
    name: dlna-udp
    protocol: UDP
  - port: 7359
    targetPort: 7359
    name: discovery-udp
    protocol: UDP
  type: LoadBalancer
  sessionAffinity: ClientIP
---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "jellyfin.fullname" . }}-tcp
  annotations:
    purelb.io/allow-shared-ip: {{ include "jellyfin.name" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "jellyfin.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - port: 8096
    targetPort: 8096
    name: http-tcp
    protocol: TCP
  - port: 8920
    targetPort: 8920
    name: https-tcp
  type: LoadBalancer
  sessionAffinity: ClientIP