{{- if .Values.ingress.create -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ include "app.name" . }}.{{ .Values.ingress.domain }}-ssl"
spec:
  secretName: "{{ include "app.name" . }}.{{ .Values.ingress.domain }}-ssl"
  issuerRef:
    name: {{ .Values.ingress.sslCLusterIssuerName }}
    kind: ClusterIssuer
  dnsNames:
    - "{{ .Values.ingress.hostname }}.{{ .Values.ingress.domain }}"
{{- end -}}