nameOverride: ""
fullnameOverride: ""

domain: home

ingress:
  create: false
  sslCLusterIssuerName: letsencrypt-staging
  hostname: minio
  domain: home

nodeAffinity:
  create: true
  labelKey: "share"
  labelValue: "true"
